# Generated by Django 2.2.16 on 2020-09-14 23:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=3)),
                ('serial', models.CharField(max_length=3)),
                ('current_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity_of_products', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('partner_type', models.CharField(choices=[('customer', 'Cliente'), ('provider', 'Proveedor'), ('cp', 'Cliente y Proveedor')], default='customer', max_length=20)),
                ('document_type', models.CharField(choices=[('ruc', 'RUC'), ('dni', 'DNI'), ('ce', 'Cedula Extranjera')], default='ruc', max_length=20)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('could_be_sold', models.BooleanField()),
                ('could_be_bought', models.BooleanField()),
                ('is_manufactured', models.BooleanField()),
                ('product_type', models.CharField(choices=[('almacenable', 'Almacenable'), ('servicio', 'Servicio'), ('consumible', 'Consumible')], default='almacenable', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('cost', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-stock'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('proforma', 'Proforma')], default='factura', max_length=10)),
                ('document_number', models.CharField(max_length=15)),
                ('purchase_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('currency', models.CharField(choices=[('pen', 'Soles'), ('usd', 'Dólares')], default='pen', max_length=7)),
                ('sub_total', models.FloatField()),
                ('igv', models.FloatField()),
                ('total', models.FloatField()),
                ('amount_paid', models.FloatField(default=0)),
                ('paid_with', models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo')], default='banco', max_length=10)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida'), ('pagada', 'Pagada')], default='borrador', max_length=10)),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.PROTECT, to='app.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=15)),
                ('sale_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('vendor', models.CharField(choices=[('oficina', 'Oficina'), ('lady', 'Lady'), ('sugey', 'Sugey'), ('aracelli', 'Aracelli'), ('jasmina', 'Jasmina')], default='oficina', max_length=10)),
                ('currency', models.CharField(choices=[('pen', 'Soles')], default='pen', max_length=7)),
                ('sub_total', models.FloatField(default=0)),
                ('igv', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('amount_paid', models.FloatField(default=0)),
                ('paid_with', models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('despachada', 'Despachada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('customer', models.ForeignKey(limit_choices_to={'partner_type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, to='app.Partner')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Document')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.FloatField(default=1)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(limit_choices_to={'could_be_sold': True}, on_delete=django.db.models.deletion.PROTECT, to='app.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='app.Sale')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.FloatField(default=1)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(limit_choices_to={'could_be_bought': True}, on_delete=django.db.models.deletion.PROTECT, to='app.Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='app.Purchase')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=15)),
                ('date', models.DateTimeField()),
                ('quantity_to_produce', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('producida', 'Producida')], default='borrador', max_length=10)),
                ('document_type', models.ForeignKey(limit_choices_to={'abbreviation': 'OP'}, on_delete=django.db.models.deletion.PROTECT, to='app.Document')),
                ('material_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.MaterialList')),
            ],
        ),
        migrations.AddField(
            model_name='materiallist',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_manufactured': True}, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movement_type', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('cambio', 'Cambio de producto'), ('produccion', 'Producción'), ('disminucion', 'Disminución por producción'), ('devolucion', 'Devolución'), ('ingreso_interno', 'Ingreso Interno'), ('salida_interna', 'Salida Interna')], max_length=20)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.FloatField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('material_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.MaterialList')),
                ('product', models.ForeignKey(limit_choices_to=models.Q(('could_be_bought', True), ('is_manufactured', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
    ]
