# Generated by Django 2.2.14 on 2020-07-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('document_type', models.CharField(choices=[('ruc', 'RUC'), ('dni', 'DNI'), ('ce', 'Cedula Extranjera')], default='ruc', max_length=50)),
                ('document_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
