# Generated by Django 2.2.14 on 2020-07-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('could_be_sold', models.BooleanField()),
                ('could_be_bought', models.BooleanField()),
                ('product_type', models.CharField(choices=[('almacenable', 'Almacenable'), ('servicio', 'Servicio'), ('consumible', 'Consumible')], default='almacenable', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
