# Generated by Django 2.2.14 on 2020-07-26 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='document_type',
            field=models.CharField(choices=[('ruc', 'RUC'), ('dni', 'DNI'), ('ce', 'Cedula Extranjera')], default='ruc', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('almacenable', 'Almacenable'), ('servicio', 'Servicio'), ('consumible', 'Consumible')], default='almacenable', max_length=30),
        ),
        migrations.CreateModel(
            name='MaterialList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('quantity_of_products', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('material_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MaterialList')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.Product')),
            ],
        ),
    ]
