# Generated by Django 2.2.14 on 2020-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200726_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('client', 'Cliente'), ('provider', 'Proveedor'), ('cp', 'Cliente y Proveedor')], default='client', max_length=20),
        ),
    ]
