# Generated by Django 2.2.14 on 2020-07-26 22:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('abbreviation', models.CharField(max_length=3)),
                ('serial', models.CharField(max_length=3)),
                ('current_number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('paid_with', models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo')], default='banco', max_length=10)),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('pagada', 'Pagada')], default='abierta', max_length=10)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Document')),
                ('provider', models.ForeignKey(limit_choices_to={'partner_type': 'provider'}, on_delete=django.db.models.deletion.PROTECT, to='app.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Purchase')),
            ],
        ),
    ]
