# Generated by Django 2.2.14 on 2020-07-26 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_document_purchase_purchasedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(choices=[('pen', 'Soles'), ('usd', 'Dólares')], default='pen', max_length=7),
        ),
        migrations.AlterField(
            model_name='partner',
            name='document_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(limit_choices_to={'could_be_bought': True}, on_delete=django.db.models.deletion.PROTECT, to='app.Product'),
        ),
    ]
