# Generated by Django 2.2.14 on 2020-07-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200726_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='movement_type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('produccion', 'Producción'), ('disminucion', 'Disminución por producción'), ('devolucion', 'Devolución'), ('ingreso_interno', 'Ingreso Interno')], max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('abierta', 'Abierta'), ('pagada', 'Pagada')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_details', to='app.Purchase'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
    ]
