# Generated by Django 2.2.14 on 2020-07-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200727_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='document',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('recibida', 'Recibida'), ('pagada', 'Pagada')], default='borrador', max_length=10),
        ),
    ]
