# Generated by Django 2.2.14 on 2020-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200727_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_manufactured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
