# Generated by Django 2.2.14 on 2020-07-28 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_is_manufactured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiallist',
            name='name',
        ),
        migrations.AlterField(
            model_name='materiallist',
            name='product',
            field=models.ForeignKey(limit_choices_to={'is_manufactured': True}, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
    ]
