# Generated by Django 2.2.14 on 2020-07-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
