# Generated by Django 2.2.14 on 2020-07-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200728_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=7),
        ),
    ]
