# Generated by Django 2.2.14 on 2020-07-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20200728_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='product',
            field=models.ForeignKey(limit_choices_to={'could_be_bought': True}, on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
