# Generated by Django 2.2.14 on 2020-07-28 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200728_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiallist',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='component',
            name='material_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='app.MaterialList'),
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('quantity_to_produce', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('producida', 'Producida')], default='borrador', max_length=10)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Document')),
                ('material_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.MaterialList')),
            ],
        ),
    ]
