# Generated by Django 2.2.14 on 2020-07-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200728_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='document_type',
            field=models.ForeignKey(limit_choices_to={'abbreviation': 'OP'}, on_delete=django.db.models.deletion.PROTECT, to='app.Document'),
        ),
    ]
