# Generated by Django 2.2.14 on 2020-07-28 23:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200728_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=15)),
                ('sale_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('currency', models.CharField(choices=[('pen', 'Soles')], default='pen', max_length=7)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('paid_with', models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo')], default='banco', max_length=10)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('despachada', 'Despachada'), ('pagada', 'Pagada')], default='borrador', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('customer', 'Cliente'), ('provider', 'Proveedor'), ('cp', 'Cliente y Proveedor')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('unit_price', models.DecimalField(decimal_places=2, default=1.0, max_digits=7)),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('product', models.ForeignKey(limit_choices_to={'could_be_sold': True}, on_delete=django.db.models.deletion.PROTECT, to='app.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='app.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'partner_type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, to='app.Partner'),
        ),
        migrations.AddField(
            model_name='sale',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Document'),
        ),
    ]
