# Generated by Django 2.2.15 on 2020-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200728_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='paid_with',
            field=models.CharField(choices=[('banco', 'Banco'), ('efectivo', 'Efectivo')], default='efectivo', max_length=10),
        ),
    ]
