# Generated by Django 2.2.15 on 2020-09-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_sale_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-stock']},
        ),
        migrations.AlterField(
            model_name='component',
            name='product',
            field=models.ForeignKey(limit_choices_to=models.Q(('could_be_bought', True), ('is_manufactured', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='app.Product'),
        ),
        migrations.AlterField(
            model_name='component',
            name='quantity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='movement_type',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('cambio', 'Cambio de producto'), ('produccion', 'Producción'), ('disminucion', 'Disminución por producción'), ('devolucion', 'Devolución'), ('ingreso_interno', 'Ingreso Interno'), ('salida_interna', 'Salida Interna')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='quantity_to_produce',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='document_type',
            field=models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('proforma', 'Proforma')], default='factura', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='igv',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sub_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='igv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('despachada', 'Despachada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sub_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.FloatField(default=1),
        ),
    ]
