# Generated by Django 2.2.15 on 2020-09-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200902_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-date']},
        ),
    ]
