# Generated by Django 2.2.16 on 2020-09-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LittleBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=8)),
                ('opening_balance', models.FloatField(blank=True)),
                ('closing_balance', models.FloatField(blank=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LittleBoxMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=8)),
                ('quantity', models.FloatField()),
                ('movement_details', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=100)),
                ('little_box', models.ForeignKey(limit_choices_to={'status': 'abierta'}, on_delete=django.db.models.deletion.PROTECT, to='littlebox.LittleBox')),
            ],
        ),
    ]
